[theme]
primaryColor = "#e0a83c"
backgroundColor = "#05070a"
secondaryBackgroundColor = "#0f131a"
textColor = "#f8fafc"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
runOnSave = false  # Prevents auto-reload

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[runner]
magicEnabled = false
fastReruns = true
